<?php

use Drupal\Core\Datetime\DrupalDateTime;
use Drupal\Core\Entity\EntityInterface;
use Drupal\node\Entity\Node;
use Drupal\node\NodeInterface;

/**
 * Implements hook_cron().
 */
function ex40_m_cron() {
  $now = new DrupalDateTime('now');
  $storage = \Drupal::entityTypeManager()->getStorage('node');
  $nids = $storage->getQuery()
    ->condition('status', 1)
    ->condition('type', 'news')
    ->condition('field_archive', 0)
    ->execute();

  $nodes = Node::loadMultiple($nids);

  foreach ($nodes as $node) {
    $pub_date = $node->get('field_publication_date')->value;
    /** @var $pub_date \DateTimeInterface */
    $interval = $now->diff($pub_date);
    if ($interval->d > 30) {
      $node->set('field_archive', 1);
    }
    $node->save();
    \Drupal::entityTypeManager()->getStorage('node')->resetCache([$node]);
  }
}

/**
 * Implements hook_entity_insert().
 */
function ex40_m_entity_insert(EntityInterface $entity) {
  if ($entity instanceof NodeInterface) {
    \Drupal::queue('mailing_letters_worker')->createItem($entity->id());
  }
}
