_core:
  default_config_hash: gbxsfZiC2MMjzyiqbCPrKXXxlhQDa0pMNs0FSt_33ds
enable: true
address: dev081023@gmail.com
roles: {  }
allowed: '*@example.com'
description: true
message: true
mailkeys: ''
mailkeys_skip: ''
